# Introduction to Numpy

Things to learn

- Working with Vectors
- Slicing for Numpy
- Real world use case for Numpy

In [3]:
print("Hello", "World")

Hello World


## Simple arithmetic in Python

In [4]:
10 + 20 - 5

25

## Iterating over a list

In [5]:
scores = [12, 45, 89, 34, 75]
for num in scores:
    print(num * 10)

120
450
890
340
750


In [6]:
import numpy as np

In [7]:
ex = np.array( [[11, 12, 13, 14], [21, 22, 23, 24], [31, 32, 33, 34]] )

In [8]:
ex

array([[11, 12, 13, 14],
       [21, 22, 23, 24],
       [31, 32, 33, 34]])

In [9]:
ex.shape

(3, 4)

ex [ row_slice, col_slice ]

In [10]:
ex[:2, 1:3]

array([[12, 13],
       [22, 23]])

In [11]:
ex

array([[11, 12, 13, 14],
       [21, 22, 23, 24],
       [31, 32, 33, 34]])

In [12]:
ex[1:3, :2]

array([[21, 22],
       [31, 32]])

In [13]:
ex

array([[11, 12, 13, 14],
       [21, 22, 23, 24],
       [31, 32, 33, 34]])

In [14]:
ex[1:3, 2:]

array([[23, 24],
       [33, 34]])

In [15]:
ex

array([[11, 12, 13, 14],
       [21, 22, 23, 24],
       [31, 32, 33, 34]])

In [16]:
ex[ 1:3 , :]

array([[21, 22, 23, 24],
       [31, 32, 33, 34]])